// <auto-generated />
using System;
using EfConsoleApp.Console;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfConsoleApp.Console.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113113541_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfConsoleApp.Console.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agent");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jorge Mendes"
                        });
                });

            modelBuilder.Entity("EfConsoleApp.Console.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Club");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Spain",
                            Name = "Real Madrid"
                        });
                });

            modelBuilder.Entity("EfConsoleApp.Console.Footballer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("JerseyNumber")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Footballers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1985, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClubId = 1,
                            FirstName = "Cristiano",
                            JerseyNumber = (byte)7,
                            LastName = "Ronaldo"
                        });
                });

            modelBuilder.Entity("EfConsoleApp.Console.FootballerAgent", b =>
                {
                    b.Property<int>("FootballerId")
                        .HasColumnType("int");

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.HasKey("FootballerId", "AgentId");

                    b.HasIndex("AgentId");

                    b.ToTable("FootballersAgent");

                    b.HasData(
                        new
                        {
                            FootballerId = 1,
                            AgentId = 1
                        });
                });

            modelBuilder.Entity("EfConsoleApp.Console.TransferMarketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ContractExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FootballerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Marketvalue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FootballerId")
                        .IsUnique();

                    b.ToTable("TransferMarketData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractExpirationDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FootballerId = 1,
                            Marketvalue = 1000000m
                        });
                });

            modelBuilder.Entity("EfConsoleApp.Console.Footballer", b =>
                {
                    b.HasOne("EfConsoleApp.Console.Club", "Club")
                        .WithMany("Footballers")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("EfConsoleApp.Console.FootballerAgent", b =>
                {
                    b.HasOne("EfConsoleApp.Console.Agent", "Agent")
                        .WithMany("FootballerAgent")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfConsoleApp.Console.Footballer", "Footballer")
                        .WithMany("FootballerAgent")
                        .HasForeignKey("FootballerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Footballer");
                });

            modelBuilder.Entity("EfConsoleApp.Console.TransferMarketData", b =>
                {
                    b.HasOne("EfConsoleApp.Console.Footballer", "Footballer")
                        .WithOne("TransferMarketData")
                        .HasForeignKey("EfConsoleApp.Console.TransferMarketData", "FootballerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Footballer");
                });

            modelBuilder.Entity("EfConsoleApp.Console.Agent", b =>
                {
                    b.Navigation("FootballerAgent");
                });

            modelBuilder.Entity("EfConsoleApp.Console.Club", b =>
                {
                    b.Navigation("Footballers");
                });

            modelBuilder.Entity("EfConsoleApp.Console.Footballer", b =>
                {
                    b.Navigation("FootballerAgent");

                    b.Navigation("TransferMarketData");
                });
#pragma warning restore 612, 618
        }
    }
}
